# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30f26f63122cfd409df0d6a4199bf1495dd2a45e3f014f0d2a57409f936cbf299c20c0572184970deda7a54eab1db4b2ce8fa1a9d5374bc7a6f0f6f1e8e859d

test:
  secret_key_base: 3dded19923cb7850456b84b1587e27dbac97e2ab20f22b28dce3bc9413179c8d3e5505604732a9c2313f00a834be6d1df527f1a425ad8f422d6401c4906fe3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
